Fixes #236
google/privacy-sandbox-aggregation-service pull request #244
Opened 2022-08-02 04:54 UTC by haroonmoh

There was an issue with main.js version. I pushed the dev version of main.js. I changed it to the prod version. Prod version does not have the licenses so I have included main.js.License.txt. Let me know if I should revert back to dev version

2022-08-10 21:20 UTC, taoliaoleo commented on control-plane/dist/main.js.LICENSE.txt
> +/*! regenerator-runtime -- Copyright (c) 2014-present, Facebook, Inc. -- license (MIT): https://github.com/facebook/regenerator/blob/main/LICENSE */
Please delete this file.

2022-08-18 20:46 UTC, taoliaoleo approved these changes

2022-08-19 19:00 UTC, hostirosti requested changes
Can you check if the files in the `dist` folder are generated. If yes we should remove them from the repo and add them to `.gitignore`

2022-08-23 19:48 UTC, haroonmoh commented
I was testing rebase on this. I will try to rebase on the user management page

2022-08-26 19:24 UTC, merged